### ISSUE TITLE
The problems to run 'Secure firmware update test/

### ISSUE THREAD

**Issue by ChaiEvan** [ARM-software/arm-systemready#129]
By the document [SystemReady Security Interface Extension User Guide](https://documentation-service.arm.com/static/64633812bc004c4648163981?token=)
3.7 Secure firmware update test, mentions a series of tests about firmware update.  We can find an prebuild image from https://github.com/ARM-software/arm-systemready/tree/main/SIE/prebuilt_images/v22.10_SIE_REL1.1.0

Flowing 3.7, Q1: my first question is whether the capsule update test can be simulated by qemu?  

(I noticed there is a repo https://git.gitlab.arm.com/systemready/firmware-build/qemu/sbsa-ref-ve-es, which could be related to section 3.7. But I found its SbsaQemu.dsc (sbsa-ref-ve-es/build-firmware.sh) doesn't have the capability to do capsule update because its CapsuleLib is NULL. ) 
Q2: is there an SIE repo to cover firmware update tests like sbsa-ref-ve-es did if the answer to Q1 is yes?

**Comment by edhay** [comment]
Hi @ChaiEvan , 
  
  We suggest not to use the old release of SIE ACS: https://github.com/ARM-software/arm-systemready/tree/main/SIE/prebuilt_images/v22.10_SIE_REL1.1.0
We have already integrated the SIE ACS image into the ACS images of SR, ES, and IR Bands.
For e.g. of the latest image of SR Band, you could use the image here:
https://github.com/ARM-software/arm-systemready/tree/main/SR/prebuilt_images/v23.09_2.0.0

Choose SIE ACS on the grub menu when the ACS image boots. 
For more information please refer to:
https://developer.arm.com/documentation/102872/0100/Test-Security-Interface-Extension-compliance


Q1: The repo  https://git.gitlab.arm.com/systemready/firmware-build/qemu/sbsa-ref-ve-es is no longer available.
Q2: The guide 
https://developer.arm.com/documentation/102872/0100/Test-Security-Interface-Extension-compliance/Secure-firmware-update-test
talks about the process of CapsuleUpdate tests. Request you to refer to the same.

Please feel free to contact us for any further queries. 

--ACS Team
