### ISSUE TITLE
[Regression] aarch64 build broken

### ISSUE THREAD

**Issue by PhatFree** [ARM-software/arm-systemready#144]
PR https://github.com/ARM-software/arm-systemready/pull/98 Introduced edk2-test-parser, but the build scripts were hardcoded with x86_64 paths, with no hardware agnostic paths or provisions. Meaning that ACS can no longer be built on aarch64 systems.

https://github.com/ARM-software/arm-systemready/blob/63a15d3f46a28e9e0624cdc2538477ef7c72070f/common/scripts/build-linux-sbsa.sh#L121
https://github.com/ARM-software/arm-systemready/blob/63a15d3f46a28e9e0624cdc2538477ef7c72070f/common/scripts/build-linux-sbsa.sh#L123
https://github.com/ARM-software/arm-systemready/blob/63a15d3f46a28e9e0624cdc2538477ef7c72070f/common/scripts/build-linux-sbsa.sh#L127

**Comment by chetan-rathore** [comment]
Hi @PhatFree,

Thanks for highlighting the issue. 
We are planning to upstream the required changes by this week. 

Thanks,
ACS team
