### ISSUE TITLE
Building ACS IR 1.x image

### ISSUE THREAD

**Issue by ownia** [ARM-software/arm-systemready#145]
Is there a way to build ACS IR 1.x image?
It looks like the IR buildroot is corrupted (using `IR/scripts/build-scripts`).

**Comment by chetan-rathore** [comment]
Hello @ownia,

IR 1.x builds which were based on **Busybox** are no longer supported for the latest ACS code changes.
We will recommend using IR 2.x releases as they have the latest ACS changes, but if you need to use an IR 1.x build please use the v21.09_1.0 tag.

Please refer to the IR Readme:
https://github.com/ARM-software/arm-systemready/tree/main/IR#note-ir-busybox-build-is-deprecated-and-no-longer-supported-the-last-stable-build-tag-is-v2109_10-please-refer-to-yocto-readme-for-instructions-to-build-latest-ir-yocto-image

IR 2.x releases are based on Yocto.

Thanks,
Chetan
