### ISSUE TITLE
Please update the SR Linux base to v6.8 for resolving the BSA and SBSA Linux failures for v23.09_2.0.0 / v24.03_2.1.0 ACS images.

### ISSUE THREAD

**Issue by nvidiaarm** [ARM-software/arm-systemready#181]
Comment from Chetan:

"As suspected the issue was still observed since the fix in linux mainline is available from on v6.8-rc6 revisions onwards
https://github.com/torvalds/linux/blob/v6.8-rc6/drivers/pci/msi/irqdomain.c#L64 and the latest ACS SR image is based on Linux v6.7.

Can you please raise a request on arm-systemready github to update the SR linux base to v6.8"

**Comment by chetan-rathore** [comment]
Hello @nvidiaarm,

SR ACS image is updated to build with v6.8 kernel.

https://github.com/ARM-software/arm-systemready/actions/workflows/SystemReady_Images_Daily_Build.yml
Daily Build number 11 onwards will have the changes

Please take SR image from this link: https://github.com/ARM-software/arm-systemready/actions/runs/8942694960

Thanks,
ACS team
