### ISSUE TITLE
[Feature Request] Provide building instructions for self compile

### ISSUE THREAD

**Issue by gabefair** [ARM-software/arm-systemready#183]
Hello,
Could you provide or link to the building instructions for compiling this ourselves?

**Comment by chetan-rathore** [comment]
Hello @gabefair, 

README inside each band folder contains detailed instructions on building the SystemReady Image for that band.

ES : https://github.com/ARM-software/arm-systemready/tree/main/ES#acs-build-steps
SR: https://github.com/ARM-software/arm-systemready/tree/main/SR#acs-build-steps
IR: https://github.com/ARM-software/arm-systemready/blob/main/IR/Yocto/README.md#acs-build-steps

Please let us know if you need any further help.

Thanks,
ACS team
