### ISSUE TITLE
SR ACS 1.1.0 - kernel parameters used in Grub.cfg and startup.nsh are different 

### ISSUE THREAD

**Issue by sunnywang-arm** [ARM-software/arm-systemready#70]
When booting from Grub, it can’t mount the USB key partitions, so no logs are saved to acs_results directory. 
When booting from Startup.nsh, logs can be saved to acs_results directory.

**Comment by marcjones-ampere** [comment]
I don't see this issue. Do you have a serial log of the failure to locate the results device? 
```
Setting RESULT_DEVICE to /dev/sda2
Mounted the results partition on device /dev/sda2
```

**Comment by edhay** [comment]
The issue is resolved through PR: https://github.com/ARM-software/arm-systemready/pull/88
Commit id: https://github.com/ARM-software/arm-systemready/commit/d52845c6f58ae528dac3544a7344e2bfde3b6773
