### ISSUE TITLE
IR ACS should upgrade from langdale

### ISSUE THREAD

**Issue by rossburton** [ARM-software/arm-systemready#82]
As per https://wiki.yoctoproject.org/wiki/Releases, langdale is EOL and no longer supported.

**Comment by edhay** [comment]
Thank you, Ross. We will plan for the upgrade from langdale.

With Warm Regards,
Edhay

**Comment by chetan-rathore** [comment]
Hello @rossburton,

Yocto is upgraded to mickledore.

Thanks,
ACS team
